export const USER_GET_START = `USER_GET_START`;
export const USER_GET_SUCCESS = `USER_GET_SUCCESS`;
export const USER_GET_ERROR = `USER_GET_ERROR`;

export const USER_GET_CURRENT_START = `USER_GET_CURRENT_START`;
export const SET_CURRENT_USER = `SET_CURRENT_USER`;
export const SET_CURRENT_USER_ERROR = `SET_CURRENT_USER_ERROR`;

export const USER_FIND_START = `USER_FIND_START`;
export const USER_FIND_SUCCESS = `USER_FIND_SUCCESS`;
export const USER_FIND_ERROR = `USER_FIND_ERROR`;
